[build]
  base = "client"
  command = "npm run build-only"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  CYPRESS_INSTALL_BINARY = "0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
